import './globals.css'
import { Inter } from 'next/font/google'
import Footer from "./components/footer";
import Nav from "./components/nav"  

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Pricing',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Nav></Nav>
        {children}
        <Footer></Footer>
        </body>
      
    </html>
  )
}
